### Ruby-Challenge API Documentation
##### Product Specifications
The API have the following features:
* Create an User
* Confirm User with email
* Login User
* Create an TODO List
* Change mode of TODO list (pending, initiated, done)
* Delete TODO List
* Create an Item
* Change mode of Item (pending, read, executed, archived)
* Delete Item
* List items ans lists according to their status
* Pagination


##### Staging: http://ruby-challenge-staging.herokuapp.com/
##### Production: http://ruby-challenge-production.herokuapp.com/
##### DEV Environment: http://localhost:3000/

Change MODE constant to the environment who will receive the request

In [68]:
# import libyrary for python requests demonstration
# change constant mode to your enviroment mode

#MODE = 'dev'
#MODE = 'prod'
MODE = 'stag'


import requests
import json
import pandas as pd


# define the url

if MODE == 'dev':
    url = 'http://localhost:3000'
elif MODE == 'prod':
    url = 'https://ruby-challenge-production.herokuapp.com'
elif MODE == 'stag':
    url = 'https://ruby-challenge-staging.herokuapp.com'

#### GET / - returns the root page of the API ('http://localhost:3000')

In [69]:

# the same of ' r = requests.get('http://localhost:3000') '
r = requests.get(url) # get the response

# get the response body as json
json_response = json.loads(r.text)

# print the response body
print('JSON: ', json_response)

## PRINT RESPONSE INFO
# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)


pd.json_normalize(json_response)

JSON:  {'message': 'Welcome to the API'}

              message
0  Welcome to the API

#### GET /users/sign_in - returns a message informing what information you need to sign in

In [70]:
r = requests.get((url + '/api/users/login'))

# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)

# get the response body as json
json_response = json.loads(r.text)

# show json response
print('JSON: ', json_response )

pd.json_normalize(json_response)

JSON:  {'message': 'Enter email and password'}

                    message
0  Enter email and password

#### GET /users/sign_up - returns a message informing what you need to sign up

In [71]:
r = requests.get((url + '/api/users/sign_up'))

# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)

json_response = json.loads(r.text)

print('JSON: ', json_response)
pd.json_normalize(json_response)

JSON:  {'message': 'Enter email, username and password'}

                              message
0  Enter email, username and password

#### POST /users - creates a new user

After the user signs up, he/she will receive an email with a link to confirm his/her email address


So the user must confirm his/her email address before he/she can login

In [72]:
sign_up_params = {'user[email]': 'mail@mail.com', 'user[username]': 'username', 'user[password]': 'password'}

r = requests.post((url + '/api/users'), params=sign_up_params)



# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)


# get the response body as json
json_response = json.loads(r.text)

# show json response
print('JSON: ', json_response)


##  error because this account already exists
##  use this account to login
##  email: mail@mail.com
##  password: password


pd.json_normalize(json_response)

JSON:  {'errors': 'You have not signed up'}

                   errors
0  You have not signed up

#### POST /users/login - logs in a user

**Utilize login params - email, password to get authentication token**

**Utilize the authentication token to make requests to the API**

**The authentication token will expire after a certain period of time**

**If the authentication token expires, you will need to sign in again**

**To get working the authentication token, you will need to set it in the header of your request**

**headers = {'Authorization': TOKEN }**

In [73]:
login_params = {'user[email]': 'mail@mail.com', 'user[password]': 'password'}
r = requests.post((url + '/api/users/login'), params=login_params)


# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code)

# get the response body as json
json_response = json.loads(r.text)

# # show json response
# print('JSON_RESPONSE: ', json_response, '\n')

# # get the token
# token = json_response['token']

# # print the token
# print('TOKEN: ', token)


pd.json_normalize(json_response)

,message,token
0,You have successfully logged in,eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjU0M...

##### **EXAMPLE OF A REQUEST WITH THE AUTHENTICATION TOKEN**


##### **GET TODO LIST - returns a list of all the TODO lists**


##### **DOCUMENTATION OF GET TODO LIST IS ON HIS OWN SECTION**

In [74]:

# hold the token header in a variable
auth_head_tag = {'Authorization':token}

# makes the request with the token
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag)

# get the response body as json
# json_response = json.loads(r.text)

# show json response
# print('JSON: ', json_response)

# get page status code to check if the request was successful
# when the request is successful, the status code is 200
print('STATUS_CODE: ', r.status_code)
pd.json_normalize(json_response)

STATUS_CODE:  429

,message,token
0,You have successfully logged in,eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjU0M...

#### POST /api/todo_lists - creates a new todo list
 
**ACCEPT PARAMS:**

    * title
    * description
    * action


**SETTED AUTOMATICALLY:**
    * user_id
    * mode
    * created_at
    * updated_at
    * items_count

DEFAULT VALUES:
    * mode = pending
    * items_count = 0
    * created_at = updated_at = current time
    * user_id = the user who created the list


**EXAMPLE PARAMS:**
    
        { "item": 
            { "title": "",
              "description": "",
              "action": "",
            }
        }

**URL PARAMS EXAMPLE:**
?item[title]=VALUE&item[description]=VALUE&item[action]=VALUE


**RETURN TODO LIST OBJECT IF CREATED**

In [76]:
title = 'title-testing' # define the title
title_modificator = 'title-modification' # define the title modificatorq


# hold todo list params in a variable and define the title
todo_lists_params = {'todo_list[title]': title, 'todo_list[description]': 'description', 'todo_list[action]': 'run on server'}


# hold the token header in a variable
auth_head_tag = {'Authorization':token}

# makes the request with the token and the todo list params
r = requests.post((url +'/api/todo_lists'), headers=auth_head_tag, params=todo_lists_params )


# or u can pass values through url
#r = requests.post((url +'/api/todo_lists?item[title]=VALUE&item[description]=VALUE&item[action]=VALUE'), headers=auth_head_tag)


# get the response body as json
json_response = json.loads(r.text)


# show json response
print('JSON: ', json_response)

pd.json_normalize(json_response)

JSON:  {'errors': {'title': ['has already been taken']}}

               errors.title
0  [has already been taken]

**EXTRA PYTHON SECTION TO CREATE TODO LIST OBJECTS, IT IS NOT NECESSARY TO THE CHALLENGE**

**CAN USE IT TO TEST RACK CORS AND RACK ATTACK**

In [77]:
# Title Modificator
mod = "RECEITA "

# Title adtional tag in case title already exists
add_tag = "X"


# This function use a loop to create todo list objects continuously in a range
def todo_lists_post_request(auth_head_tag, mod, add_tag, counter):
    # Number of errors
    errors = 0
    
    # Count the number of todos created
    objects_created_count = 0
    
    # Count the number of todos created and use it to change the title
    title_numerator = 1

    # Loop to create todo list objects
    for i in counter:

        # define the title with modificator
        title = (mod + str(title_numerator))

        # todo list params
        todo_lists_params = {'todo_list[title]': title  , 'todo_list[description]': 'description', 'todo_list[action]': 'run on server'}

        # makes the request with the token and the todo list params
        r = requests.post((url + '/api/todo_lists'), headers=auth_head_tag, params=todo_lists_params)

        # check status code and if it is not 200, count the error and add tag to the title in case it already exists
        if r.status_code == 422:
            mod += add_tag
            errors += 1
        else:
            # Count the number of todos created
            objects_created_count += 1

        # Count the number of todos created and use it to change the title
        title_numerator += 1

    # print the number of todos created
    print('OBJECTS CREATED: ', objects_created_count)
    # print the number of errors
    print('ERRORS: ', errors)
        
# Run the function
todo_lists_post_request(auth_head_tag, mod, add_tag, range(20,50))

OBJECTS CREATED:  25
ERRORS:  5

#### GET /api/todo_lists - returns all todo lists with serializer and pagination

All Todo List object is inside the data array

Simple wrap the Todo List object with the serializer

Pagy add pagination to the response headers

Print headers to see what pagy gem is doing

In [78]:
# hold the token header in a variable
auth_head_tag = {'Authorization':token}

# makes the request with the token
r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag)

# print('HEADERS: ', r.headers, '\n\nBODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code) 
# print( 'BODY: ', r.text, '\n\nSTATUS_CODE: ', r.status_code) 

# get the response body as json
json_response = json.loads(r.text)


# show json response
total_pages = r.headers['Total-Pages']

current_page = r.headers['Current-Page']

print('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')
            

json_objects = json_response['data']

# print ('HEADERS: ', r.headers, '\n')

# for js_object in json_objects:
#     print('JSON_OBJECT: ', js_object, '\n')


pd.json_normalize(json_response['data'])

CURRENT PAGE:  1

TOTAL PAGES:  6

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,1,todo-lists,title-testing,description,pending,2022-04-02T15:53:32.943Z,2022-04-02T15:53:32.943Z,0
1,2,todo-lists,RECEITA 1,description,pending,2022-04-02T15:53:42.661Z,2022-04-02T15:53:42.661Z,0
2,3,todo-lists,RECEITA 2,description,pending,2022-04-02T15:53:43.347Z,2022-04-02T15:53:43.347Z,0
3,4,todo-lists,RECEITA 3,description,pending,2022-04-02T15:53:44.030Z,2022-04-02T15:53:44.030Z,0
4,6,todo-lists,RECEITA 5,description,pending,2022-04-02T15:53:45.398Z,2022-04-02T15:53:45.398Z,0
5,7,todo-lists,RECEITA 6,description,pending,2022-04-02T15:53:46.077Z,2022-04-02T15:53:46.077Z,0
6,8,todo-lists,RECEITA 7,description,pending,2022-04-02T15:53:46.751Z,2022-04-02T15:53:46.751Z,0
7,9,todo-lists,RECEITA 8,description,pending,2022-04-02T15:53:47.661Z,2022-04-02T15:53:47.661Z,0
8,10,todo-lists,RECEITA 9,description,pending,2022-04-02T15:53:48.326Z,2022-04-02T15:53:48.326Z,0
9,11,todo-lists,RECEITA 12,description,pending,2022-04-02T15:53:50.338Z,2022-04-02T15:53:50.338Z,0

#### GET /api/todo_lists?page=PAGENUMBER - returns a todo lists list with pagination

Utilize the page number to get the next page of todo lists

In [79]:
page_params = {'page': '1'}
r = requests.get((url +  '/api/todo_lists'), headers=auth_head_tag, params=page_params)
json_response = json.loads(r.text)


total_pages = r.headers['Total-Pages']

current_page = r.headers['Current-Page']

print('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')
            
json_objects = json_response['data']

# print ('HEADERS: ', r.headers, '\n')

# print('JSON_RESPONSE: ', json_response, '\n')


# for js_object in json_objects:
#     print('JSON_OBJECT: ', js_object, '\n')


pd.json_normalize(json_response['data'])

CURRENT PAGE:  1

TOTAL PAGES:  6

,id,type,attributes.title,attributes.description,attributes.mode,attributes.created-at,attributes.updated-at,attributes.items-count
0,1,todo-lists,title-testing,description,pending,2022-04-02T15:53:32.943Z,2022-04-02T15:53:32.943Z,0
1,2,todo-lists,RECEITA 1,description,pending,2022-04-02T15:53:42.661Z,2022-04-02T15:53:42.661Z,0
2,3,todo-lists,RECEITA 2,description,pending,2022-04-02T15:53:43.347Z,2022-04-02T15:53:43.347Z,0
3,4,todo-lists,RECEITA 3,description,pending,2022-04-02T15:53:44.030Z,2022-04-02T15:53:44.030Z,0
4,6,todo-lists,RECEITA 5,description,pending,2022-04-02T15:53:45.398Z,2022-04-02T15:53:45.398Z,0
5,7,todo-lists,RECEITA 6,description,pending,2022-04-02T15:53:46.077Z,2022-04-02T15:53:46.077Z,0
6,8,todo-lists,RECEITA 7,description,pending,2022-04-02T15:53:46.751Z,2022-04-02T15:53:46.751Z,0
7,9,todo-lists,RECEITA 8,description,pending,2022-04-02T15:53:47.661Z,2022-04-02T15:53:47.661Z,0
8,10,todo-lists,RECEITA 9,description,pending,2022-04-02T15:53:48.326Z,2022-04-02T15:53:48.326Z,0
9,11,todo-lists,RECEITA 12,description,pending,2022-04-02T15:53:50.338Z,2022-04-02T15:53:50.338Z,0

##### GET /api/items?page=PAGENUMBER&todo_list_id=ID - returns a list of items with pagination

In [101]:
page_with_todo_list_params = {'page': '1', 'todo_list_id': '4'}
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)
json_response = json.loads(r.text)


# print('JSON_RESPONSE: ', json_response, '\n')

json_todo_list_object = json_response['todo_list']

json_items_objects = json_response['items']

total_pages = r.headers['Total-Pages']
            
print('TOTAL PAGES: ', total_pages)

# print("TODO LIST: ", json_todo_list_object, '\n')


# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            
pd.json_normalize(json_items_objects)

# print('JSON_RESPONSE: ', json_response, '\n')

TOTAL PAGES:  1

,id,name,action,mode,created_at,updated_at,todo_list
0,3,item,run on server,pending,2022-04-02T17:43:32.606Z,2022-04-02T17:43:32.606Z,RECEITA 3
1,4,item,run on server,pending,2022-04-02T17:43:33.691Z,2022-04-02T17:43:33.691Z,RECEITA 3
2,5,item,run on server,pending,2022-04-02T17:43:34.753Z,2022-04-02T17:43:34.753Z,RECEITA 3
3,6,item,run on server,pending,2022-04-02T17:43:42.798Z,2022-04-02T17:43:42.798Z,RECEITA 3
4,7,item,run on server,pending,2022-04-02T17:43:45.469Z,2022-04-02T17:43:45.469Z,RECEITA 3
5,8,item,run on server,pending,2022-04-02T17:43:47.192Z,2022-04-02T17:43:47.192Z,RECEITA 3
6,9,item,run on server,pending,2022-04-02T17:43:48.838Z,2022-04-02T17:43:48.838Z,RECEITA 3
7,10,item,run on server,pending,2022-04-02T17:43:50.133Z,2022-04-02T17:43:50.133Z,RECEITA 3
8,11,item,run on server,pending,2022-04-02T17:43:51.585Z,2022-04-02T17:43:51.585Z,RECEITA 3
9,12,item,run on server,pending,2022-04-02T17:43:52.721Z,2022-04-02T17:43:52.721Z,RECEITA 3
10,13,item,run on server,pending,2022-04-02T17:43:54.009Z,2022-04-02T17:43:54.009Z,RECEITA 3
11,14,item,run on server,pending,2022-04-02T17:43:55.292Z,2022-04-02T17:43:55.292Z,RECEITA 3
12,15,item,run on server,pending,2022-04-02T17:43:56.449Z,2022-04-02T17:43:56.449Z,RECEITA 3
13,16,item,run on server,pending,2022-04-02T17:43:57.759Z,2022-04-02T17:43:57.759Z,RECEITA 3
14,17,item,run on server,pending,2022-04-02T17:43:58.728Z,2022-04-02T17:43:58.728Z,RECEITA 3
15,18,item,run on server,pending,2022-04-02T17:44:00.099Z,2022-04-02T17:44:00.099Z,RECEITA 3
16,19,item,run on server,pending,2022-04-02T17:44:02.442Z,2022-04-02T17:44:02.442Z,RECEITA 3

In [81]:
pd.json_normalize(json_todo_list_object)

,id,title,description,mode,created_at,updated_at,items_count
0,4,RECEITA 3,description,pending,2022-04-02T15:53:44.030Z,2022-04-02T15:53:44.030Z,0

#### POST /api/items - creates a new item in a todo list

**ACCEPT PARAMS:**

    * todo_list_id
    * action
    * name

**SETTED AUTOMATICALLY:**

    * mode
    * created_at
    * updated_at

**DEFAULT VALUES:**

    * mode = pending
    * created_at = updated_at = current time

**EXAMPLE PARAMS:**
    
        { "item": 
            { "todo_list_id": "",
              "action": "",
              "name": "",
            }
        }

**URL PARAMS EXAMPLE:**
?item[todo_list_id]=VALUE&item[action]=VALUE&item[name]=VALUE

In [100]:
item_params = {'item[todo_list_id]': '4', 'item[action]': 'run on server','item[name]': 'item'}
r = requests.post((url + '/api/items'), headers=auth_head_tag, params=item_params)
json_response = json.loads(r.text)
print('JSON_RESPONSE: ', json_response, '\n')

JSON_RESPONSE:  {'item': {'id': 19, 'name': 'item', 'action': 'run on server', 'mode': 'pending', 'created_at': '2022-04-02T17:44:02.442Z', 'updated_at': '2022-04-02T17:44:02.442Z', 'todo_list': 'RECEITA 3'}}

### GET /api/view_item - returns a specific item with given id
Access object in view_item show page

It change object mode to read

You can set params with "true" value to change it to other modes (**read is setted by default if u access this endpoint**)

**Available params:**
    * executed
    * archived

When mode is archived, the item is not shown in the common lists (**only can be accessed if a list of archived items is requested**)

In [104]:
params = {'id': '18'}
r = requests.get((url + '/api/view_item/'), headers=auth_head_tag, params=params)
r.text

json_object = json.loads(r.text)['data']
pd.json_normalize(json_object)

,id,type,attributes.name,attributes.action,attributes.mode,attributes.created-at,attributes.updated-at,attributes.todo-list
0,18,items,item,run on server,read,2022-04-02T17:44:00.099Z,2022-04-02T17:44:46.383Z,RECEITA 3

#### GET /api/items/:id&:executed - updates an item with given id and executed status

In [ ]:
params = {'id': '2', 'executed': 'true'}
r = requests.get((url + '/api/view_item/'), headers=auth_head_tag, params=params)
json_object = json.loads(r.text)['data']
pd.json_normalize(json_object)

#### GET /api/items/:id&:archived - updates an item with given id and archived status

In [ ]:
params = {'id': '3', 'archived': 'true'}
r = requests.get((url + '/api/view_item/'), headers=auth_head_tag, params=params)
json_object = json.loads(r.text)['data']
pd.json_normalize(json_object)

#### GET /api/items - returns all items with pagination and filter - example: object sorted by enum mode (asc)


 Utilize the page number to get the next page of items

 mode is defined in todo list and item models, it can be:

 [:pending, :read, :executed, :archived] for items

 [:pending, :initiated, :done] for todo lists

In [111]:
page_with_todo_list_params = {'page': '1', 'todo_list_id': '4', 'filter': 'mode_asc'}
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)
json_response = json.loads(r.text)




json_todo_list_object = json_response['todo_list']

json_items_objects = json_response['items']


total_pages = r.headers['Total-Pages']

current_page = r.headers['Current-Page']

print ('CURRENT PAGE: ', current_page, '\n\nTOTAL PAGES: ', total_pages, '\n')
            

# print("TODO LIST: ", json_todo_list_object, '\n')


# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            


pd.json_normalize(json_todo_list_object)

CURRENT PAGE:  1

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,4,RECEITA 3,description,pending,2022-04-02T15:53:44.030Z,2022-04-02T15:53:44.030Z,17

In [112]:
pd.json_normalize(json_items_objects)

,id,name,action,mode,created_at,updated_at,todo_list
0,19,item,run on server,pending,2022-04-02T17:44:02.442Z,2022-04-02T17:44:02.442Z,RECEITA 3
1,4,item,run on server,pending,2022-04-02T17:43:33.691Z,2022-04-02T17:43:33.691Z,RECEITA 3
2,5,item,run on server,pending,2022-04-02T17:43:34.753Z,2022-04-02T17:43:34.753Z,RECEITA 3
3,6,item,run on server,pending,2022-04-02T17:43:42.798Z,2022-04-02T17:43:42.798Z,RECEITA 3
4,7,item,run on server,pending,2022-04-02T17:43:45.469Z,2022-04-02T17:43:45.469Z,RECEITA 3
5,8,item,run on server,pending,2022-04-02T17:43:47.192Z,2022-04-02T17:43:47.192Z,RECEITA 3
6,9,item,run on server,pending,2022-04-02T17:43:48.838Z,2022-04-02T17:43:48.838Z,RECEITA 3
7,10,item,run on server,pending,2022-04-02T17:43:50.133Z,2022-04-02T17:43:50.133Z,RECEITA 3
8,11,item,run on server,pending,2022-04-02T17:43:51.585Z,2022-04-02T17:43:51.585Z,RECEITA 3
9,12,item,run on server,pending,2022-04-02T17:43:52.721Z,2022-04-02T17:43:52.721Z,RECEITA 3
10,13,item,run on server,pending,2022-04-02T17:43:54.009Z,2022-04-02T17:43:54.009Z,RECEITA 3
11,14,item,run on server,pending,2022-04-02T17:43:55.292Z,2022-04-02T17:43:55.292Z,RECEITA 3
12,15,item,run on server,pending,2022-04-02T17:43:56.449Z,2022-04-02T17:43:56.449Z,RECEITA 3
13,16,item,run on server,pending,2022-04-02T17:43:57.759Z,2022-04-02T17:43:57.759Z,RECEITA 3
14,17,item,run on server,pending,2022-04-02T17:43:58.728Z,2022-04-02T17:43:58.728Z,RECEITA 3
15,3,item,run on server,pending,2022-04-02T17:43:32.606Z,2022-04-02T17:43:32.606Z,RECEITA 3
16,18,item,run on server,read,2022-04-02T17:44:00.099Z,2022-04-02T17:44:46.383Z,RECEITA 3

#### GET /api/items?page=PAGENUMBER&mode=MODE - returns a list of items with pagination and filter - example: object sorted by enum mode (desc)

Utilize the page number to get the next page of items

mode is defined in todo list and item models, it can be:

[:pending, :read, :executed, :archived] for items

[:pending, :initiated, :done] for todo lists

In [113]:
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2', 'filter': 'mode_desc'}
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)
json_response = json.loads(r.text)


# print('JSON_RESPONSE: ', json_response, '\n')

# data = json_response['data']


# for d in data :
#     print('DATA: ', d, '\n')

json_todo_list_object = json_response['todo_list']

json_items_objects = json_response['items']


total_pages = r.headers['Total-Pages']

current_page = r.headers['Current-Page']
            
print('TOTAL PAGES: ', total_pages)

            

# print("TODO LIST: ", json_todo_list_object, '\n')


# for item in json_items_objects:
#     print('ITEM: ', item, '\n')
            


pd.json_normalize(json_todo_list_object)

TOTAL PAGES:  1

,id,title,description,mode,created_at,updated_at,items_count
0,2,RECEITA 1,description,pending,2022-04-02T15:53:42.661Z,2022-04-02T15:53:42.661Z,0

##### GET /api/items?page=PAGENUMBER&mode=MODE&todo_list_id=ID - returns a list of items with pagination and filter - example: object sorted by enum mode (asc)

Utilize the page number to get the next page of items

mode is defined in todo list and item models, it can be:

[:pending, :read, :executed, :archived] for items

[:pending, :initiated, :done] for todo lists

In [ ]:
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2', 'filter': 'mode_asc'}
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)
json_response = json.loads(r.text)


# print('JSON_RESPONSE: ', json_response, '\n')

# data = json_response['data']


# for d in data :
#     print('DATA: ', d, '\n')

json_todo_list_object = json_response['todo_list']

json_items_objects = json_response['items']


total_pages = r.headers['Total-Pages']
            
print('TOTAL PAGES: ', total_pages)

print("TODO LIST: ", json_todo_list_object, '\n')

            

for item in json_items_objects:
    print('ITEM: ', item, '\n')
            
# json_objects = json_response['data']

# # print ('HEADERS: ', r.headers, '\n')

# print('JSON_RESPONSE: ', json_response, '\n')


# for js_object in json_objects:
#     print('JSON_OBJECT: ', js_object, '\n')

##### GET /api/items?page=PAGENUMBER&filter_factor&todo_list_id=ID - returns a list of items with pagination and filter - example: object sorted by selected factor

**HOW TO FILTER WITH FACTOR?**

Items and todo lists can be filtered by mode order in asc, desc like already done in the previous examples
But it can be filtered in different orders by factor


**COMMOM ORDERS:**

    common_order = [:pending, :read, :executed, :archived]
    its_like = [0, 1, 2, 3]

    asc = comom_order
    desc = [3 ,2 ,1 ,0]


**ITEMS FACTORED ORDERS(MATRIX):**

    0 =  [1, 2, 3, 0] 
    1 =  [2, 3, 0, 1]
    2 =  [3, 0, 1, 2]
    3 =  [0, 1, 2, 3]
    4 =  [1, 3, 2, 0]
    5 =  [2, 1, 0, 3]
    6 =  [3, 2, 1, 0]
    7 =  [0, 3, 2, 1]
    8 =  [1, 0, 3, 2]
    9 =  [2, 0, 1, 3]
    10 = [3, 1, 0, 2]
    11 = [0, 2, 1, 3]
    12 = [1, 3, 0, 2]
    13 = [2, 3, 1, 0]
    14 = [3, 0, 2, 1]
    15 = [0, 1, 3, 2]
    16 = [1, 2, 0, 3]
    17 = [2, 1, 3, 0]
    18 = [3, 2, 0, 1]
    19 = [0, 3, 1, 2]
    20 = [1, 0, 2, 3]
    21 = [2, 0, 3, 1]
    22 = [3, 1, 2, 0]
    23 = [0, 2, 3, 1]




**Utilize matrix order number in params**

**EXAMPLE PARAMS(REMEMBER, ONLY TODO LIST ID IS REQUIRED TO ACCESS THE LIST EVER):**

    { page: 1,
      filter_factor: 0,
      todo_list_id: 1
    }

In [ ]:
page_with_todo_list_params = {'page': '1', 'todo_list_id': '2', 'filter_factor': '8'}
r = requests.get((url + '/api/items'), headers=auth_head_tag, params=page_with_todo_list_params)
json_response = json.loads(r.text)

json_todo_list_object = json_response['todo_list']

json_items_objects = json_response['items']


total_pages = r.headers['Total-Pages']
            
print('TOTAL PAGES: ', total_pages, '\n')

print("TODO LIST: ", json_todo_list_object, '\n')

            

for item in json_items_objects:
    print('ITEM: ', item, '\n')

**TODOS COMMOM ORDERS:**

    common_order = [:pending, :initiatied, :done]
    its_like = [0, 1, 2]

    asc = comom_order
    desc = [2 ,1 ,0]


**TODO LISTS FACTORED ORDERS(MATRIX):**

    0 = [2, 0, 1]
    1 = [2, 0, 1]
    2 = [2, 0, 1]
    3 = [2, 0, 1]
    4 = [2, 0, 1]
    5 = [2, 0, 1]

In [ ]:
params = { 'page': 1, 'filter_factor': 8 }


r = requests.get((url + '/api/todo_lists'), headers=auth_head_tag, params=params)
json_response = json.loads(r.text)

json_object = json_response['data']


for js_object in json_object:
    print('JSON_OBJECT: ', js_object, '\n')

##### GET /api/delete_todo_list - deletes a todo list with given id

In [ ]:
params = {'id': '5'}
r = requests.get((url + '/api/delete_todo_list'), headers=auth_head_tag, params=params)
json_response = json.loads(r.text)
print('JSON_RESPONSE: ', json_response, '\n')

##### GET /api/remove_item - deletes an item with given id

In [ ]:
params = {'id': '1'}
r = requests.get((url + '/api/remove_item'), headers=auth_head_tag)
json_response = json.loads(r.text)
print('JSON_RESPONSE: ', json_response, '\n')